### ISSUE TITLE
无法在ARM Mac上编译pick2real

### ISSUE THREAD

**Issue by wangliang1989** [Dal-mzhang/REAL#2]
pick2real的作用是什么？
在编译pick2real时，ARM Mac上无法直接使用.o文件，可能需要.o的源代码：
````bash
gcc -Os -mcmodel=medium -w -o ../../bin/pick2real pick2real.o -lm
Undefined symbols for architecture arm64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [pick2real] Error 1
````

**Comment by Y5517lalalo** [comment]
I think I am getting a similar error 

gcc -Os -mcmodel=medium -w -o ../../bin/pick2real pick2real.o -lm
pick2real.o: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status
make: *** [Makefile:6: pick2real] Error 1

**Comment by Dengda98** [comment]
remove the original  `pick2real.o` file will be fine.

**Comment by Y5517lalalo** [comment]
Good day

This solution works for me. Thank you.

Regards
Madisha L.
